// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: documents.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addDocument = `-- name: AddDocument :one
INSERT INTO documents (file_path, uploaded_by) VALUES ($1, $2) RETURNING id, file_path, uploaded_at, uploaded_by
`

type AddDocumentParams struct {
	FilePath   string
	UploadedBy uuid.UUID
}

func (q *Queries) AddDocument(ctx context.Context, arg AddDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, addDocument, arg.FilePath, arg.UploadedBy)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.UploadedAt,
		&i.UploadedBy,
	)
	return i, err
}

const findDocumentByID = `-- name: FindDocumentByID :one
SELECT id, file_path, uploaded_at, uploaded_by FROM documents WHERE id = $1 LIMIT 1
`

func (q *Queries) FindDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, findDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.UploadedAt,
		&i.UploadedBy,
	)
	return i, err
}

const findDocuments = `-- name: FindDocuments :many
SELECT id, file_path, uploaded_at, uploaded_by FROM documents
`

func (q *Queries) FindDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, findDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.UploadedAt,
			&i.UploadedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDocumentsByUserID = `-- name: FindDocumentsByUserID :many
SELECT id, file_path, uploaded_at, uploaded_by FROM documents WHERE uploaded_by = $1
`

func (q *Queries) FindDocumentsByUserID(ctx context.Context, uploadedBy uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, findDocumentsByUserID, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.UploadedAt,
			&i.UploadedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserDocumentByID = `-- name: FindUserDocumentByID :one
SELECT id, file_path, uploaded_at, uploaded_by FROM documents WHERE id = $1 AND uploaded_by = $2 LIMIT 1
`

type FindUserDocumentByIDParams struct {
	ID         uuid.UUID
	UploadedBy uuid.UUID
}

func (q *Queries) FindUserDocumentByID(ctx context.Context, arg FindUserDocumentByIDParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, findUserDocumentByID, arg.ID, arg.UploadedBy)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.UploadedAt,
		&i.UploadedBy,
	)
	return i, err
}

const removeDocument = `-- name: RemoveDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) RemoveDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeDocument, id)
	return err
}

const removeUserDocument = `-- name: RemoveUserDocument :exec
DELETE FROM documents WHERE id = $1 AND uploaded_by = $2
`

type RemoveUserDocumentParams struct {
	ID         uuid.UUID
	UploadedBy uuid.UUID
}

func (q *Queries) RemoveUserDocument(ctx context.Context, arg RemoveUserDocumentParams) error {
	_, err := q.db.ExecContext(ctx, removeUserDocument, arg.ID, arg.UploadedBy)
	return err
}
